version: '3'
services:
  es-app:
    image: shop/shop-product
    container_name: es-app
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - sc-net
    ports:
      - 8769:8769

networks:
  sc-net:
    external: false
